# Generated by Django 5.0.6 on 2024-06-06 05:51

import django.db.models.deletion
import sgc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=100)),
                ('area_atuacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('coordenador', models.ManyToManyField(related_name='escolas', to='sgc.coordenador')),
            ],
        ),
        migrations.AddField(
            model_name='coordenador',
            name='professores',
            field=models.ManyToManyField(related_name='coordenadores', to='sgc.professor'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricula', models.UUIDField(default=sgc.models.generate_matricula, editable=False, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sobrenome', models.CharField(max_length=70)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('tipo_acesso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sgc.tipoacesso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='sgc.usuario', to_field='matricula'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sumario', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_id', to='sgc.usuario', to_field='matricula')),
            ],
        ),
        migrations.AddField(
            model_name='coordenador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to='sgc.usuario', to_field='matricula'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='sgc.usuario', to_field='matricula')),
            ],
        ),
    ]
