# Generated by Django 5.0.3 on 2024-05-26 07:55

import django.db.models.deletion
import sgc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricula', models.UUIDField(default=sgc.models.generate_matricula, editable=False, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sobrenome', models.CharField(max_length=70)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('tipo_acesso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sgc.tipoacesso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
