# Generated by Django 5.0.3 on 2024-05-23 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='professor', serialize=False, to='sgc.usuario')),
                ('formacao', models.CharField(max_length=100)),
                ('area_atuacao', models.CharField(max_length=100)),
            ],
        ),
    ]
