# Generated by Django 5.0.3 on 2024-05-18 18:23

import sgc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('matricula', models.UUIDField(default=sgc.models.generate_matricula, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('formacao', models.CharField(max_length=100)),
                ('area_atuacao', models.CharField(max_length=100)),
                ('titulacao', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
