# Generated by Django 5.0.3 on 2024-05-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0002_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usuario', serialize=False, to='sgc.usuario', unique=True),
        ),
    ]
