# Generated by Django 5.0.3 on 2024-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0002_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
