# Generated by Django 5.0.3 on 2024-05-23 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0002_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aluno', serialize=False, to='sgc.usuario')),
                ('curso', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=20)),
            ],
        ),
    ]
