# Generated by Django 5.0.6 on 2024-06-03 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0008_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_id', to='sgc.usuario', to_field='matricula'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sumario',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
