# Generated by Django 5.0.6 on 2024-06-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0009_alter_post_autor_alter_post_sumario_alter_post_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sumario',
            field=models.CharField(max_length=255),
        ),
    ]
