# Generated by Django 5.0.6 on 2024-06-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0011_alter_post_sumario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
